### ISSUE TITLE
Website CSS Design

### ISSUE THREAD

**Issue by whippingdot** [rayhanadev/Replit-Token-Scanner#1]
![image](https://user-images.githubusercontent.com/64354499/177988988-fff2bc2c-4d25-4f9c-84f6-77f4b20769c9.png)

I like the CSS on this website but would recommend removing that arrow at the tip of the hover effect. It is a little too much and the website would look better without the arrow hover effect.

**Comment by rayhanadev** [comment]
The website uses furret.css, my personal CSS library for quick and easy stylings. I do not intend on keeping it the way it is for long, simply some base styles for launch.

If you have a problem with the styling feel free to take it up in the [furret.css repository](https://github.com/rayhanadev/furretcss) however the "quirks" if you will are what makes it unique to my library :).

If the motion is really what bothers you, consider turning on reduced motion on your device.

**Comment by whippingdot** [comment]
> The website uses furret.css, my personal CSS library for quick and easy stylings. I do not intend on keeping it the way it is for long, simply some base styles for launch.
> 
> If you have a problem with the styling feel free to take it up in the [furret.css repository](https://github.com/rayhanadev/furretcss) however the "quirks" if you will are what makes it unique to my library :).
> 
> If the motion is really what bothers you, consider turning on reduced motion on your device.

Didn't realize it was a library you made. I do agree the arrow does make the styling unique to your library. The arrow isn't that bad, I just felt like it was too much. Don't have a real issue with the styling tho so ill refrain from making an issue in that repository.
